using System;
using System.Text;
using Sandbox.Game;
using Torch.Commands;
using Torch.Commands.Permissions;
using Utils.Torch;
using VRage.Game.ModAPI;
using VRageMath;

namespace TorchMonitor
{
    [Category("tm")]
    public sealed class TorchMonitorCommandModule : CommandModule
    {
        static readonly GpsCleanerCollection _gpsCleanerCollection;

        static TorchMonitorCommandModule()
        {
            _gpsCleanerCollection = new GpsCleanerCollection();
        }

        TorchMonitorPlugin Plugin => (TorchMonitorPlugin)Context.Plugin;

        [Command("on", "Starts monitoring")]
        [Permission(MyPromoteLevel.Admin)]
        public void StartMonitoring()
        {
            Plugin.Enabled = true;
        }

        [Command("off", "Stops monitoring")]
        [Permission(MyPromoteLevel.Admin)]
        public void StopMonitoring()
        {
            Plugin.Enabled = false;
        }

        [Command("nexus", "Shows Nexus help")]
        [Permission(MyPromoteLevel.Admin)]
        public void ShowNexusHelp()
        {
            var adminId = GetCallerPlayer().IdentityId;
            var msg = new StringBuilder();
            msg.AppendLine("!tm nexus corners -- shows 8 corners of the monitored nexus sector");
            msg.AppendLine("!tm nexus centers -- shows the center position of all monitored segments");

            MyVisualScriptLogicProvider.SendChatMessage(msg.ToString(), "", adminId);
        }

        [Command("nexus corners", "Shows 8 corners of the monitored nexus sector")]
        [Permission(MyPromoteLevel.Admin)]
        public void ShowNexusSectorCorners()
        {
            var adminId = GetCallerPlayer().IdentityId;
            _gpsCleanerCollection.Clear(adminId);

            var corners = Plugin.Nexus.GetCorners();
            for (var i = 0; i < corners.Count; i++)
            {
                var corner = corners[i];
                var name = $"!tm nexus corners {i}";
                _gpsCleanerCollection.Add(adminId, name, "", corner, Color.Magenta);
            }
        }

        [Command("nexus centers", "Shows the center of all monitored nexus segments")]
        [Permission(MyPromoteLevel.Admin)]
        public void ShowNexusSegmentCenters()
        {
            var adminId = GetCallerPlayer().IdentityId;
            _gpsCleanerCollection.Clear(adminId);

            foreach (var (index, center) in Plugin.Nexus.GetCenters())
            {
                var name = $"!tm nexus centers {index.X}_{index.Y}_{index.Z}";
                _gpsCleanerCollection.Add(adminId, name, "", center, Color.Magenta);
            }
        }

        [Command("nexus cleargps", "Clears all gps generated by nexus commands")]
        [Permission(MyPromoteLevel.Admin)]
        public void DeleteNexusGps()
        {
            var adminId = GetCallerPlayer().IdentityId;
            _gpsCleanerCollection.Clear(adminId);
        }

        IMyPlayer GetCallerPlayer()
        {
            if (!(Context.Player is { } admin))
            {
                throw new InvalidOperationException("must be called in game");
            }

            return admin;
        }
    }
}